src/Entity/PartnerO.php
<?php

namespace App\Entity;

use App\Repository\PartnerORepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM ;


#[ORM\Entity(repositoryClass: PartnerORepository::class)]
class PartnerO
{
    #[ORM\Id]
  #[ORM\GeneratedValue]
    
    #[ORM\Column]
    
    private ?int $id = null;

    #[ORM\Column(length: 255)]
   
    private ?string $nom = null;
    
 #[ORM\Column(length: 255)]
                           
                            private ?string $email = null;

    #[ORM\Column]
   
    private ?int $user_id = null;

    #[ORM\Column(nullable: true)]
  
    private ?bool $is_active = null;

   #[ORM\Column]
   
    private ?int $id_permission = null;

   #[ORM\ManyToMany(targetEntity: Permission::class, inversedBy: 'partnerOs')]
   private Collection $Permission;

   public function __construct()
   {
       $this->Permission = new ArrayCollection();
   }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(?bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getIdPermission(): ?int
    {
        return $this->id_permission;
    }

    public function setIdPermission(int $id_permission): self
    {
        $this->id_permission = $id_permission;

        return $this;
    }

    /**
     * @return Collection<int, Permission>
     */
    public function getPermission(): Collection
    {
        return $this->Permission;
    }

    public function addPermission(Permission $permission): self
    {
        if (!$this->Permission->contains($permission)) {
            $this->Permission->add($permission);
        }

        return $this;
    }

    public function removePermission(Permission $permission): self
    {
        $this->Permission->removeElement($permission);

        return $this;
    }
}

src/Entity/Structure.php
<?php

namespace App\Entity;

use App\Repository\StructureRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: StructureRepository::class)]
class Structure
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private int $id;    

    #[ORM\OneToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'user_id', referencedColumnName: 'id', nullable:false)]
    private User $user;

    #[ORM\ManyToOne(targetEntity: Partner::class, inversedBy: 'structure')]
    #[ORM\JoinColumn(name: 'partner_id', referencedColumnName: 'id', nullable:false)]
    private $partner;

    #[ORM\ManyToMany(targetEntity: Permission::class, inversedBy: 'structure', fetch:'EAGER')]
    private Collection $permission;

    public function __construct()
    {
        $this->permission = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Set user.
     *
     * @param User $user
     *
     * @return Partner
     */
    public function setUser(User $user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user.
     *
     * @return User
     */
    public function getUser(): User
    {
        return $this->user;
    }

    public function getPartner(): ?Partner
    {
        return $this->partner;
    }

    public function setPartner(?Partner $partner): self
    {
        $this->partner = $partner;

        return $this;
    }

    /**
     * @return Collection<int, Permission>
    */
    public function getPermission(): Collection
    {
        return $this->permission;
    }

    public function addPermission(Permission $permission): self
    {
        if (!$this->permission->contains($permission)) {
            $this->permission->add($permission);
        }

        return $this;
    }

    public function removePermission(Permission $permission): self
    {
        $this->permission->removeElement($permission);

        return $this;
    }

    public function clearPermissions()
    {
        $this->permission->clear();
        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[ORM\HasLifecycleCallbacks]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private int $id;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank]
    #[Assert\Email(
        message: 'The email {{ value }} is not a valid email.',
    )]
    private string $email;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private string $adresse;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private string $nom;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private string $password;

    #[ORM\Column]
    private bool $is_active;

    #[ORM\Column(type: 'datetime')]
    private \DateTime $created_at;

    #[ORM\Column(type: 'datetime')]
    private \DateTime $updated_at;

    public function __construct()
    {
        $this->is_active = true;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return $this->email;
    }

    /**
     * @see UserInterface
     */

    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getAdresse(): string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getNom(): string
     {
         return $this->nom;
     }

     public function setNom(string $nom): self
     {
         $this->nom = $nom;

         return $this;
     }

     public function getIsActive(): bool
     {
        return $this->is_active;
     }

     public function setDisable(): bool
     {
        return $this->is_active = false;
     }

     public function setEnable(): bool
     {
        return $this->is_active = true;
     }

     public function getCreatedAt(): \DateTime
     {
        return $this->created_at;
     }

     public function getUpdatedAt(): \DateTime
     {
        return $this->updated_at;
     }

     #[ORM\PrePersist]
     public function setCreatedAt()
     {
        $this->created_at = new \DateTime();
     }

     #[ORM\PrePersist]
     #[ORM\PreUpdate]
     public function setUpdatedAt()
     {
        $this->updated_at = new \DateTime();
     }

}

src/Controller/StructureController.php
<?php

namespace App\Controller;

use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\StructureRepository;

#[Route('/structure', name: 'structure_')]
class StructureController extends AbstractController
{
    #[Route('', name: 'index')]
    public function index(StructureRepository $structure_repository): Response
    {
        /** @var User */
        $user = $this->getUser();
        return $this->render('structure/index.html.twig', [
            'structure' => $structure_repository->findOneBy(['user' => $user->getId()]),
        ]);

    }

}

templates/structure/_delete_form.html.twig
<form method="post" action="{{ path('app_structure_delete', {'id': structure.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ structure.id) }}">
    <button class="btn">Delete</button>
</form>

templates/structure/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/structure/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Structure{% endblock %}

{% block body %}
    <h1>Edit Structure</h1>

    {{ include('structure/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_structure_index') }}">back to list</a>

    {{ include('structure/_delete_form.html.twig') }}
{% endblock %}

templates/structure/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Orange Blue - Partenaire{% endblock %}
{% block body %}
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-10">
      <h2>Mes informations</h2>
      <div class="table-responsive">
        <table class="table align-middle mb-0 bg-white">
          <thead class="bg-light">
            <tr>
              <th>Nom</th>
              <th>Email</th>
              <th>Adresse</th>
            </tr>
          </thead>
          <tbody>
              <tr>
                <td>
                  <div class="d-flex align-items-center">              
                    <div class="ms-3">
                      <p class="fw-bold mb-1">{{structure.user.nom}}</p>
                    </div>
                  </div>
                </td>
                <td>
                  <p class="text-muted mb-0">{{structure.user.email}}</p>
                </td>
                <td>
                  <p class="text-muted mb-0">{{structure.user.adresse}}</p>
                </td>
              </tr>
        </tbody>
      </table>
      <h2 class="mt-5">Mes permissions</h2>
      <table class="table align-middle mb-0 bg-white">
          <thead class="bg-light">
            <tr>
              <th>Titre</th>
            </tr>
          </thead>
          <tbody>
          {% if structure.permission is not empty %}
            {% for permission in structure.permission %}
              <tr>
                <td>
                  <div class="d-flex align-items-center">              
                    <div class="ms-3">
                      <p class="fw-bold mb-1">{{permission.nom}}</p>
                    </div>
                  </div>
                </td>
              </tr>
              {% endfor %}
              {% else %}
              <tr>
                <td colspan="4"><p class="text-center">Pas de liste des permissions</td>
              </tr>
              {% endif %}
        </tbody>
      </table>
    </div>
    </div>
  </div>
</div>
{% endblock %}

templates/structure/liste_permissions.html.twig
{% extends 'base.html.twig' %}

{% block title %}Administrateur Orange Blue - Permissions{% endblock %}
{% block body %}
<div class="container">
  <div class="row justify-content-md-center">    
    <div class="col-10">
      <h2>Liste des Permissions pour la structure [{{structure.user.nom}}]</h2>
      <table class="table align-middle mb-0 bg-white">
      <thead class="bg-light">
        <tr>
          <th>Titre de la permission</th>
        </tr>
      </thead>
      <tbody>
      {% if structure.permission is not empty %}
        {% for permission in structure.permission %}
          <tr>
            <td>
              <div class="d-flex align-items-center">              
                <div class="ms-3">
                  <p class="fw-bold mb-1">{{permission.nom}}</p>
                </div>
              </div>
            </td>
          </tr>
          {% endfor %}
          {% else %}
          <tr>
            <td colspan="2"><p class="text-center">Pas de liste des permissions</td>
          </tr>
          {% endif %}
      </tbody>
    </table>
    </div>
  </div>
</div>
{% endblock %}

templates/structure/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Structure{% endblock %}

{% block body %}
    <h1>Create new Structure</h1>

    {{ include('structure/_form.html.twig') }}

    <a href="{{ path('app_structure_index') }}">back to list</a>
{% endblock %}

templates/structure/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Structure{% endblock %}

{% block body %}
    <h1>Structure</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ structure.id }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ structure.adresse }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ structure.email }}</td>
            </tr>
            <tr>
                <th>User_id</th>
                <td>{{ structure.userId }}</td>
            </tr>
            <tr>
                <th>Partenaire_id</th>
                <td>{{ structure.partenaireId }}</td>
            </tr>
            <tr>
                <th>Is_active</th>
                <td>{{ structure.isActive ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Id_permission</th>
                <td>{{ structure.idPermission }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_structure_index') }}">back to list</a>

    <a href="{{ path('app_structure_edit', {'id': structure.id}) }}">edit</a>

    {{ include('structure/_delete_form.html.twig') }}
{% endblock %}